apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: traefik/whoami:latest
          imagePullPolicy: Always
          args: ["--port=5678"]
          env:
            - name: WHOAMI_NAME
              value: "practice_pod"
          ports:
            - containerPort: 5678